/*
Copyright 2018 Rancher Labs, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	ranchervm_v1alpha1 "github.com/rancher/vm/pkg/apis/ranchervm/v1alpha1"
	versioned "github.com/rancher/vm/pkg/client/clientset/versioned"
	internalinterfaces "github.com/rancher/vm/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/rancher/vm/pkg/client/listers/virtualmachine/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// ARPTableInformer provides access to a shared informer and lister for
// ARPTables.
type ARPTableInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ARPTableLister
}

type aRPTableInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewARPTableInformer constructs a new informer for ARPTable type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewARPTableInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				return client.VirtualmachineV1alpha1().ARPTables().List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				return client.VirtualmachineV1alpha1().ARPTables().Watch(options)
			},
		},
		&ranchervm_v1alpha1.ARPTable{},
		resyncPeriod,
		indexers,
	)
}

func defaultARPTableInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewARPTableInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *aRPTableInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&ranchervm_v1alpha1.ARPTable{}, defaultARPTableInformer)
}

func (f *aRPTableInformer) Lister() v1alpha1.ARPTableLister {
	return v1alpha1.NewARPTableLister(f.Informer().GetIndexer())
}
