/*
Copyright 2018 Rancher Labs, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	ranchervm_v1alpha1 "github.com/rancher/vm/pkg/apis/ranchervm/v1alpha1"
	versioned "github.com/rancher/vm/pkg/client/clientset/versioned"
	internalinterfaces "github.com/rancher/vm/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/rancher/vm/pkg/client/listers/virtualmachine/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// SettingInformer provides access to a shared informer and lister for
// Settings.
type SettingInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.SettingLister
}

type settingInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewSettingInformer constructs a new informer for Setting type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSettingInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				return client.VirtualmachineV1alpha1().Settings().List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				return client.VirtualmachineV1alpha1().Settings().Watch(options)
			},
		},
		&ranchervm_v1alpha1.Setting{},
		resyncPeriod,
		indexers,
	)
}

func defaultSettingInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewSettingInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *settingInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&ranchervm_v1alpha1.Setting{}, defaultSettingInformer)
}

func (f *settingInformer) Lister() v1alpha1.SettingLister {
	return v1alpha1.NewSettingLister(f.Informer().GetIndexer())
}
