#!/usr/bin/python

import re
import os
import sys
import json
import logging
import stat
import docker
import time
import random
import string
import cgi

form = cgi.FieldStorage()

def print_html_headers(title):
    print """Content-type:text/html

<html>
<head>
<title>{title}</title>
</head>
<body>
""".format(**vars())

def print_html_footers():
    print """</body>
</html>
"""

def exit_script(title, msg, code):
    print_html_headers(title)
    print msg
    print """
<form method="link" action="ranchervm">
<input type="submit" value="Ok">
</form>
"""
    print_html_footers()
    sys.exit(code)


if form.getvalue("action") == "create_form":
    random_string = ''.join(random.choice(string.ascii_lowercase +
              string.digits) for _ in range(6))

    print_html_headers("RancherVM")

    print """
<form method="POST" action="ranchervm">
<input type="hidden" name="action" value="create">
<table>
<tr> <td>Hostname:</td> 
     <td><input type="text" name="hostname" value="{random_string}"></td></tr>
<tr> <td>Image:</td> 
     <td><input type="text" name="image" value="rancher/rancheros:0.2.1"></td></tr>
<tr> <td>Memory Size:</td> 
     <td><input type="text" name="mem" value="512m"></td></tr>
<tr> <td># of vCPUs:</td> 
     <td><input type="text" name="cpu" value="1"></td></tr>
<tr> <td>Port mappings:</td> 
     <td><input type="text" name="ports" value="80"> A comma-separated list of port mappings specified in <tt>docker run -p</tt> command line syntax. Range not supported</td></tr>
</table>
<input type="submit" value="Create">
</form>
""".format(**vars())
    sys.exit()

docker_client = docker.Client(base_url='unix://var/run/docker.sock')

src_str = ""
next_ptr = 0
token_patterns = \
[("ip", re.compile("(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}\
(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)")),
("numbers", re.compile("\d+")),
("protocol", re.compile("tcp|udp"))]


def parse_port_mappings(src_list_str):
    """ Parses a list of comma-separated port mappings."""

    # Each entry in the list takes the docker command line "-p" format. 
    # The result can be passed into the start method of docker-py client
    # library.

    def parse_port_map(src_elem_str):
        global src_str
        global next_ptr
        src_str = src_elem_str
        next_ptr = 0
        type, _ = peek_token()
        if type == "ip":
            result = parse_ip_port_map()
        elif type == "numbers":
            result = parse_no_ip_port_map()
        else:
            parse_error("expecting a port or IP address")
        expect_token("EOF")
        return result

    def parse_ip_port_map():
        """parses ip:hostPort:containerPort | ip::containerPort"""
        ip = expect_token("ip")
        expect_token(":")
        type, _ = peek_token()
        if type == "numbers":
            host_port = parse_port()
            expect_token(":")
            container_port = parse_container_port()
            return {container_port : (ip, host_port)}
        if type == ":":
            expect_token(":")
            container_port = parse_container_port()
            return {container_port : (ip, None)}
    
    def parse_no_ip_port_map():
        """parses hostPort:containerPort | containerPort"""
        port = parse_port()
        type, _ = peek_token()
        if type == ":":
            get_token()
            container_port = parse_container_port()
            return {container_port : port}
        if type == "/":
            get_token()
            container_port = port + "/" + parse_protocol()
            return {container_port : None}
        return {port : None}
    
    def parse_port():
        port = parse_port_number()
#        type, _ = peek_token()
#        if type == "-":
#            get_token()
#            high_port = parse_port_number()
#            return port + "-" + high_port
        return port
    
    def parse_container_port():
        port = parse_port()
        type, _ = peek_token()
        if type == "/":
            get_token()
            return port + "/" + parse_protocol()
        return port
    
    def parse_protocol():
        type, token = get_token()
        if type == "protocol":
            return token
        parse_error("expecting a protocol name")
    
    def parse_port_number():
        type, token = get_token()
        if type == "numbers" and (0 < int(token) < 65536):
            return token
        parse_error("expecting a port number")
    
    def peek_token():
        global src_str
        global next_ptr
        global token_patterns

        if next_ptr == len(src_str): return ("EOF", "")
        if src_str[next_ptr] == "/": return ("/", "/")
        if src_str[next_ptr] == ":": return (":", ":")
#        if src_str[next_ptr] == "-": return ("-", "-")
        if src_str[next_ptr] == ",": return (",", ",")
        for type, pattern in token_patterns:
            match = pattern.match(src_str[next_ptr:])
            if match: 
                return (type, src_str[next_ptr:next_ptr + match.end()])
        parse_error("unexpected charactor: " + src_str[next_ptr])
    
    def get_token():
        global next_ptr
        (type, token) = peek_token()
        next_ptr = next_ptr + len(token)
        return (type, token)
    
    def expect_token(type):
        token_type, token = get_token()
        if token_type != type:
            parse_error("expecting " + type)
        return token
    
    def parse_error(msg):
        global next_ptr
        raise Exception(msg + " at charactor " + str(next_ptr + 1))

    return {x.keys()[0] : x.values()[0] for x in
                map(parse_port_map, src_list_str.split(","))}

def get_my_id():
    with open ("/proc/self/cgroup", "r") as cgroup_file:
        return re.findall(":cpu:/docker/\S+", 
                          cgroup_file.read())[0][13:]

if form.getvalue("action") == "create":
    hostname = form.getvalue('hostname')
    image = form.getvalue('image')
    mem = form.getvalue('mem')
    cpu = form.getvalue('cpu')
    ports = form.getvalue('ports')

    def check_hostname(hostname):
        if len(hostname) > 16 or \
           re.compile("[^a-zA-Z\d\-]").search(hostname):
           exit_script("Error", "Hostname must be an alpha numerical" \
                       " string up to 16 characters long.", 1) 

    def check_image(image):
        if re.compile("[^a-zA-Z\d\-\.\/:]").search(image):
           exit_script("Error", "Bad image name", 1)

    def check_mem(mem):
        if not re.compile("^[\d]+[mMgG]$").match(mem):
           exit_script("Error", "Bad memory size", 1)

    def check_cpu(cpu):
        if not re.compile("^[\d]+$").match(cpu):
           exit_script("Error", "Bad vCPU count", 1)

    check_hostname(hostname)
    check_image(image)
    check_mem(mem)
    check_cpu(cpu)
    try:
        port_mappings = parse_port_mappings(ports)
    except Exception as e: exit_script("Error", str(e), 1)

    def extract(x):
        arr = x.split('/')
        if len(arr) == 2:
            return (arr[0], arr[1])
        return x
    container_ports = [extract(x) for x in port_mappings.keys()]

    kvm_args = "-m " + mem + " -smp " + cpu
    try:
        try:
            docker_client.inspect_image(image)
        except docker.errors.APIError:
            docker_client.pull(image)
        container = docker_client.create_container(
            image = image,
            volumes = "/image",
            environment = ["RANCHER_VM=true"],
            command = kvm_args,
            hostname = hostname,
            detach = True,
            stdin_open = True,
            ports = container_ports,
            tty = True)

        docker_client.start(container,
                            devices=['/dev/kvm:/dev/kvm:rwm',
                                     '/dev/net/tun:/dev/net/tun:rwm'],
                            cap_add=['NET_ADMIN'],
                            port_bindings = port_mappings,
                            volumes_from = get_my_id())
    except docker.errors.APIError as e: exit_script("Error", str(e), 1)
    exit_script("Created", "Instance " + hostname + " created", 0)

if form.getvalue("action") == "delete":
    id = form.getvalue("id")
    try:
        docker_client.remove_container(id);
    except docker.errors.APIError as e: exit_script("Error", str(e), 1)
    exit_script("Deleted", "Instance " + id + " removed", 0)

if form.getvalue("action") == "start":
    id = form.getvalue("id")
    container_details = docker_client.inspect_container(id)
    # Read port mappings from HostConfig
    port_bindings = container_details.get("HostConfig").get("PortBindings")
    def txform(x):
        host_ip = x[0].get("HostIp") 
        host_port = x[0].get("HostPort") 
        if host_ip == "" and host_port == "":
            return None
        if host_ip == "":
            return host_port
        if host_port == "":
            return (host_ip, )
        return (host_ip, host_port)

    port_mappings = {x: txform(port_bindings.get(x)) for x in port_bindings}

    try:
        docker_client.start(id,
                            devices=['/dev/kvm:/dev/kvm:rwm',
                                     '/dev/net/tun:/dev/net/tun:rwm'],
                            cap_add=['NET_ADMIN'],
                            port_bindings = port_mappings,
                            volumes_from = get_my_id())
    except docker.errors.APIError as e: exit_script("Error", str(e), 1)
    exit_script("Started", "Instance " + id + " started", 0)

if form.getvalue("action") == "stop":
    id = form.getvalue("id")
    try:
        docker_client.stop(id, 15)
    except docker.errors.APIError as e: exit_script("Error", str(e), 1)
    exit_script("Stopped", "Instance " + id + " stopped", 0)



containers = {c.get("Id"): c for c in docker_client.containers(all=True)}

container_details_list = \
         sorted(filter(lambda c: 
                          filter(lambda e: e == u'RANCHER_VM=true', 
                                     c.get("Config").get("Env")) != [], 
                          map(docker_client.inspect_container, 
                              [id for id in containers.keys()])),
                key = lambda c: c.get("State").get("StartedAt"),
                reverse = True)

print_html_headers("RancherVM")

print """

<h1>RancherVM</h1>

<form method="link" action="ranchervm">
<input type="hidden" name="action" value="create_form">
<input type="submit" value="Create Instance">
</form>
"""
if container_details_list == []:
    print "No instances found."
else:
    print """
<table>
<tr>
<th>Action</th>
<th>Name</th>
<th>IP</th>
<th>Image</th>
<th>Status</th>
<th>Ports</th>
<th>Created</th>
<th>KVM_ARGS</th>
</tr>
"""

    def format_mapping(mapping):
        ip = mapping.get("IP")
        if ip and ip != "0.0.0.0":
           ip = ip + ":"
        else:
           ip = ""
        protocol = mapping.get("Type")
        if not protocol or protocol == "tcp": 
            protocol = "" 
        else:
            protocol = "/" + protocol
        return ip + str(mapping.get("PublicPort")) + ":" \
                  + str(mapping.get("PrivatePort")) + protocol

    for container_details in container_details_list:
        id = container_details.get("Id")

        container = docker_client.inspect_container(id)
        hostname = container_details.get("Config").get("Hostname")
        ip = container_details.get("NetworkSettings").get("IPAddress")
        kvm_args = " ".join(container_details.get("Config").get("Cmd"))

        container = containers.get(id)
        image = container.get("Image")
        status = container.get("Status")
        created = time.ctime(container.get("Created"))
        ports = ",".join(map(format_mapping, container.get("Ports")))

        if status.startswith("Up"):
            start_stop_action = "<a href=\"ranchervm?action=stop&id=" \
                + id + "\">Stop</a>"
            console_delete_action = "<a href=\"/vnc_auto.html?title=" \
                + hostname + "&path=" + "vmmgmt/vm/"  \
                + id + "/vnc\" target=\"_blank\">Console</a>"

        else:
            start_stop_action = "<a href=\"ranchervm?action=start&id=" \
                + id + "\">Start</a>"
            console_delete_action = "<a href=\"ranchervm?action=delete&id=" \
                + id + "\">Delete</a>"

        print '<tr>'
        print ("<td>" + start_stop_action + " " \
                      + console_delete_action + "</td>")
        print ("<td>" + hostname + "</td>")
        print ("<td>" + str(ip) + "</td>")
        print ("<td>" + image + "</td>")
        print ("<td>" + status + "</td>")
        print ("<td>" + ports + "</td>")
        print ("<td>" + created + "</td>")
        print ("<td>" + kvm_args + "</td>")
        print '</tr>'

    print """</table>
"""

print_html_footers()
