#!/bin/bash

if [ "$1" = "bash" ]; then
  exec bash
fi

cd /var/lib/rancher

NOVNC=/var/lib/rancher/noVNC-0.0.2

/var/lib/rancher/gen_dnsmasq_conf > gen_dnsmasq_conf.log 2>&1 &

# Start the websocket proxy and the web server with CGI support
python $NOVNC/utils/websockify --web $NOVNC --cert /var/lib/rancher/self.pem 80 --unix-target /vmmgmt/vm
