/*
Copyright 2018 Rancher Labs, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/rancher/vm/pkg/apis/ranchervm/v1alpha1"
	scheme "github.com/rancher/vm/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MachineImagesGetter has a method to return a MachineImageInterface.
// A group's client should implement this interface.
type MachineImagesGetter interface {
	MachineImages() MachineImageInterface
}

// MachineImageInterface has methods to work with MachineImage resources.
type MachineImageInterface interface {
	Create(*v1alpha1.MachineImage) (*v1alpha1.MachineImage, error)
	Update(*v1alpha1.MachineImage) (*v1alpha1.MachineImage, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.MachineImage, error)
	List(opts v1.ListOptions) (*v1alpha1.MachineImageList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.MachineImage, err error)
	MachineImageExpansion
}

// machineImages implements MachineImageInterface
type machineImages struct {
	client rest.Interface
}

// newMachineImages returns a MachineImages
func newMachineImages(c *VirtualmachineV1alpha1Client) *machineImages {
	return &machineImages{
		client: c.RESTClient(),
	}
}

// Get takes name of the machineImage, and returns the corresponding machineImage object, and an error if there is any.
func (c *machineImages) Get(name string, options v1.GetOptions) (result *v1alpha1.MachineImage, err error) {
	result = &v1alpha1.MachineImage{}
	err = c.client.Get().
		Resource("machineimages").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MachineImages that match those selectors.
func (c *machineImages) List(opts v1.ListOptions) (result *v1alpha1.MachineImageList, err error) {
	result = &v1alpha1.MachineImageList{}
	err = c.client.Get().
		Resource("machineimages").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested machineImages.
func (c *machineImages) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Resource("machineimages").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a machineImage and creates it.  Returns the server's representation of the machineImage, and an error, if there is any.
func (c *machineImages) Create(machineImage *v1alpha1.MachineImage) (result *v1alpha1.MachineImage, err error) {
	result = &v1alpha1.MachineImage{}
	err = c.client.Post().
		Resource("machineimages").
		Body(machineImage).
		Do().
		Into(result)
	return
}

// Update takes the representation of a machineImage and updates it. Returns the server's representation of the machineImage, and an error, if there is any.
func (c *machineImages) Update(machineImage *v1alpha1.MachineImage) (result *v1alpha1.MachineImage, err error) {
	result = &v1alpha1.MachineImage{}
	err = c.client.Put().
		Resource("machineimages").
		Name(machineImage.Name).
		Body(machineImage).
		Do().
		Into(result)
	return
}

// Delete takes name of the machineImage and deletes it. Returns an error if one occurs.
func (c *machineImages) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("machineimages").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *machineImages) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Resource("machineimages").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched machineImage.
func (c *machineImages) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.MachineImage, err error) {
	result = &v1alpha1.MachineImage{}
	err = c.client.Patch(pt).
		Resource("machineimages").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
