/*
Copyright 2018 Rancher Labs, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/rancher/vm/pkg/apis/ranchervm/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMachineImages implements MachineImageInterface
type FakeMachineImages struct {
	Fake *FakeVirtualmachineV1alpha1
}

var machineimagesResource = schema.GroupVersionResource{Group: "virtualmachine.rancher.com", Version: "v1alpha1", Resource: "machineimages"}

var machineimagesKind = schema.GroupVersionKind{Group: "virtualmachine.rancher.com", Version: "v1alpha1", Kind: "MachineImage"}

// Get takes name of the machineImage, and returns the corresponding machineImage object, and an error if there is any.
func (c *FakeMachineImages) Get(name string, options v1.GetOptions) (result *v1alpha1.MachineImage, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(machineimagesResource, name), &v1alpha1.MachineImage{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MachineImage), err
}

// List takes label and field selectors, and returns the list of MachineImages that match those selectors.
func (c *FakeMachineImages) List(opts v1.ListOptions) (result *v1alpha1.MachineImageList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(machineimagesResource, machineimagesKind, opts), &v1alpha1.MachineImageList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MachineImageList{ListMeta: obj.(*v1alpha1.MachineImageList).ListMeta}
	for _, item := range obj.(*v1alpha1.MachineImageList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested machineImages.
func (c *FakeMachineImages) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(machineimagesResource, opts))
}

// Create takes the representation of a machineImage and creates it.  Returns the server's representation of the machineImage, and an error, if there is any.
func (c *FakeMachineImages) Create(machineImage *v1alpha1.MachineImage) (result *v1alpha1.MachineImage, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(machineimagesResource, machineImage), &v1alpha1.MachineImage{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MachineImage), err
}

// Update takes the representation of a machineImage and updates it. Returns the server's representation of the machineImage, and an error, if there is any.
func (c *FakeMachineImages) Update(machineImage *v1alpha1.MachineImage) (result *v1alpha1.MachineImage, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(machineimagesResource, machineImage), &v1alpha1.MachineImage{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MachineImage), err
}

// Delete takes name of the machineImage and deletes it. Returns an error if one occurs.
func (c *FakeMachineImages) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(machineimagesResource, name), &v1alpha1.MachineImage{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMachineImages) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(machineimagesResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.MachineImageList{})
	return err
}

// Patch applies the patch and returns the patched machineImage.
func (c *FakeMachineImages) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.MachineImage, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(machineimagesResource, name, data, subresources...), &v1alpha1.MachineImage{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MachineImage), err
}
