/*
Copyright 2018 Rancher Labs, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/rancher/vm/pkg/apis/ranchervm/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// CredentialLister helps list Credentials.
type CredentialLister interface {
	// List lists all Credentials in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.Credential, err error)
	// Get retrieves the Credential from the index for a given name.
	Get(name string) (*v1alpha1.Credential, error)
	CredentialListerExpansion
}

// credentialLister implements the CredentialLister interface.
type credentialLister struct {
	indexer cache.Indexer
}

// NewCredentialLister returns a new CredentialLister.
func NewCredentialLister(indexer cache.Indexer) CredentialLister {
	return &credentialLister{indexer: indexer}
}

// List lists all Credentials in the indexer.
func (s *credentialLister) List(selector labels.Selector) (ret []*v1alpha1.Credential, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.Credential))
	})
	return ret, err
}

// Get retrieves the Credential from the index for a given name.
func (s *credentialLister) Get(name string) (*v1alpha1.Credential, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("credential"), name)
	}
	return obj.(*v1alpha1.Credential), nil
}
